### ISSUE TITLE
400 Bad Requst

### ISSUE THREAD

**Issue by KevFischer** [SmartCity-2022/Service-Strassenverkehrsamt#32]
`GET https://strassenverkehrsamt.smartcity.w-mi.de/api/auth 400 (Bad Request)` 

(Selbes gilt auch für andere Routen)

Lokal alles funktionstüchtig. Ich Löse im Backend kein 400 gewollt aus deswegen wäre es gut zu wissen ob im Backend mehr Details ans Tageslicht kommen. Bzw. ob die Request überhaupt ankommt.

**Comment by Flamtky** [comment]
Der Log sagt:
> Invalid HTTP_HOST header: 'strassenverkehrsamt-backend.smartcity.svc.cluster.local'. You may need to add 'strassenverkehrsamt-backend.smartcity.svc.cluster.local' to ALLOWED_HOSTS.

Ich vermute dass du die ALLOWED_HOSTS in der [Zeile 31 settings.py](https://github.com/SmartCity-2022/Service-Strassenverkehrsamt/blob/7b347b3815a60371a124c79fc041e7fe89581bfe/SmartCity/SmartCity/settings.py#L31) anpassen musst, da Debug auf True steht.
Siehe Docs: https://docs.djangoproject.com/en/4.0/ref/settings/#allowed-hosts

Debug sollte nicht auf `True` steht, wenn es im release ist. [Zeile 29 settings.py](https://github.com/SmartCity-2022/Service-Strassenverkehrsamt/blob/7b347b3815a60371a124c79fc041e7fe89581bfe/SmartCity/SmartCity/settings.py#L29)

Andere Quelle:
https://stackoverflow.com/questions/47228488/django-allowed-hosts-vs-corsdjango-cors-headers
https://stackoverflow.com/questions/45194182/allowed-hosts-and-django
